### ISSUE TITLE
is there any way to run my own version of the tool?

### ISSUE THREAD

**Issue by pride-k** [searleser97/cpbooster#118]
I want to make certain edits in the code which I am more comfortable with and works with my setup the best. This might crash/not work for others.
I have set up a dev environment but I cant figure out if there is a way for me to utilize the code for myself and run it.

**Comment by searleser97** [comment]
I think you can install it locally, I think the command is just npm install -g in the root of the repository, I might be wrong though, but I remember adding a command for that in the package.json, please take a look

**Comment by searleser97** [comment]
Found it https://github.com/searleser97/cpbooster/blob/bb3264eeb31900f80aa7afff76dbc3ae2a973836/app/package.json#L25

**Comment by pride-k** [comment]
ohh thanks you

**Comment by pride-k** [comment]
while cpb is working, the vim plugin isn't. Is there a simple fix?

**Comment by searleser97** [comment]
Could you open a different issue with more details please ? does the plugin work with regular (non-local cpb) instalation ? what are you using ? vim or neovim ? which versions ? etc, all of this, in new issue please

**Comment by pride-k** [comment]
fixed it, there was an issue in my installation command which I never realized. Not sure exactly why it was working with the previous version of the program.
