### ISSUE TITLE
New version "cpb clone" command produces wrong folder name and file name.

### ISSUE THREAD

**Issue by quocbaodo205** [searleser97/cpbooster#27]
**Describe the bug**
Wrong folder name and code_file name, leading to unable to run test cases

**Steps To Reproduce it**
1. Update cpbooster to latest version (npm i -g cpbooster)
2. Update playwright (npx playwright install)
3. Re-init (optional, doesn't change the result)
4. Clone a problem (via cpb clone and firefox )

**Expected behavior**
1. Folder name has a "-" inbetween "Codeforces" and the round name to match with old folder name.
2. File code name start with '.', not '_'

**Screenshots**
![Screenshot_3](https://user-images.githubusercontent.com/59492699/129548946-042de037-286a-4719-9d10-fd03cec10e9a.png)

As shown, there are 2 CF734Div3 Round, and the new created one have problem F_..., which is unable to use "cpb test" command

Also  after running update cpbooster, "cpb --version" still shown 2.5.0.

**Comment by quocbaodo205** [comment]
Temporary fix for the meantime is to use v2.3.9 instead, I think this was introduced in version 2.4.0, which add and make use of function `replaceExtraDotsWithUnderscore`

**Comment by searleser97** [comment]
Thanks for the feedback :), it is fixed now, just FYI we are replacing dots to underscores to be able to support more compilers from different languages :)
