### ISSUE TITLE
Can this be used outside of a contest directory (i.e. in current directory) ?

### ISSUE THREAD

**Issue by rag-hav** [searleser97/cpbooster#30]
**Is your feature request related to a problem? Please describe.**
Cant see the testcase input.

**Describe the solution you'd like**
An option in config to toggle on the testcase input.

**Comment by searleser97** [comment]
please take a look at the official website here: https://searleser97.github.io/cpbooster/docs/add-test-case

it is probably what you are looking for.

also to understand how testing works take a look at:https://searleser97.github.io/cpbooster/docs/test

**Comment by rag-hav** [comment]
I meant with automatic test cases from competitive companion, not manual

**Comment by searleser97** [comment]
> I meant with automatic test cases from competitive companion, not manual

That is what it does already, `cpb clone` does just that
take a look at: https://searleser97.github.io/cpbooster/docs/clone

if the online judge is supported by competitive companion then you should be able to clone the tests cases with cpbooster

**Comment by searleser97** [comment]
The only possible caveat is that it always clones it to
the `contests directory` instead of your current directory, probably this is what you meant?

If that is the case, then I think I will add a flag tonthe command to be able to call it like this:

```shell
cpb clone --here
```

which will create source files and test cases files in your current directory

**Comment by rag-hav** [comment]
yes that's exactly what i meant.

**Comment by searleser97** [comment]
> yes that's exactly what i meant.
> 
> Also would be really great if we could see the test case input while testing

I added this feature with this commit: https://github.com/searleser97/cpbooster/commit/1632fb90978df9e1c526dfe92fa6ac038df9276b
