### ISSUE TITLE
Duplicate README

### ISSUE THREAD

**Issue by user202729** [searleser97/cpbooster#36]
Isn't it weird that there are two almost-identical  but not identical README file in the repository?

https://github.com/searleser97/cpbooster/blob/develop/README.md

https://github.com/searleser97/cpbooster/blob/develop/app/README.md

**Comment by searleser97** [comment]
Yes, the one inside app is used by NPM to show it in their page. If you figure a way so that in can use the one at the root of the repository that would be great

**Comment by user202729** [comment]
Hm okay.

There's an option of using symlink like this https://github.com/user202729/test

... or separate the website and the app to 2 separate repositories, and put them in the root folder.

**Comment by searleser97** [comment]
oh nicee, that is pretty helpful
