### ISSUE TITLE
Allow Compilation and Execution even when the test cases are not available

### ISSUE THREAD

**Issue by muhesh-kumar** [searleser97/cpbooster#38]
**Have you read the official website to guarantee that your feature does not exist yet?**
Official Website: https://searleser97.github.io/cpbooster/
- Yes, I have read the official website and the feature does not exist yet.

**Is your feature request related to a problem? Please describe.**
- Yes, my feature is related to a problem. Whenever I try to execute `:Test` Neovim command for a program that has no test cases, it shows 
 "No testcases available for this file. [Process exited 0]"

**Describe the solution you'd like**
- The command `:Test` can work as usual with an additional check that if _**no test cases**_ are available for the program file, it can create **_a default test case_** for this program file. For example: as of now, the test cases start numbering from 1 (eg: `file_name.in1`, `file_name.ans1` etc.,). Instead, this command can create `file_name.in0`(an empty file with no contents) and `file_name.ans0`(an empty file with no contents) as the default test case for this program file and consider this as the **_only test case_** available for the program file we are running the `:Test` command upon.

**Describe alternatives you've considered**
- I don't have any alternative solutions as of now.

**Additional context**
- For example, I'm trying to get this behavior of [CPH](https://github.com/agrawal-d/cph) extension of VSCode in cpbooster (This is very helpful if we quickly want to write brute force solutions to print some values in the console)
![cph default test case feature](https://user-images.githubusercontent.com/55415969/145514882-42dcf7ec-e785-4db6-a845-d4f2eae6a24d.jpg)
![default test case feature request](https://user-images.githubusercontent.com/55415969/145514896-7e56bb72-bab1-45a0-8f1b-2a6ee735f705.jpg)
- An addition of #16 along with this feature would be great and makes cpbooster a perfect alternative to CPH, especially for vim users.

**Comment by searleser97** [comment]
For me it looks to me like you can use de  DEBUG command to solve your issue

**Comment by muhesh-kumar** [comment]
Oh, I see. I didn't know that part about DEBUG command. Thanks for the reply!

**Comment by searleser97** [comment]
Also, all the details about such command are written here:https://searleser97.github.io/cpbooster/docs/debug
