### ISSUE TITLE
Can't run in Vim and problem in Window CMD.

### ISSUE THREAD

**Issue by kexauso613** [searleser97/cpbooster#51]
**Information:**
cpbooster version: run `cpb -v` to get this information
OS: Windows
Using Vim : yes (gVim but can run in gVim I have to run it in terminal) 
Terminal Name: CMD

**Describe the bug**
Not print the all answer when it wrong
And can't Test, Debug, ... on Vim or gVim

**Steps To Reproduce it**
1. Run wrong code in terminal, or run by command :Test on gVim  
2. Only print the last test case, or can't run by commmand

**Screenshots**
![Screenshot 2022-04-09 000322](https://user-images.githubusercontent.com/85751029/162489015-dcfd3f5b-e572-4f44-85e3-0462718941cd.png)
![Screenshot 2022-04-03 201953](https://user-images.githubusercontent.com/85751029/162489733-3be545be-99b4-4563-bc40-a9b58b95bfeb.png)

**Comment by searleser97** [comment]
https://github.com/searleser97/cpbooster/issues/9
