### ISSUE TITLE
feature request: Enabling and disabling generated comments

### ISSUE THREAD

**Issue by LuisMBaezCo** [searleser97/cpbooster#55]
Hello `cpbooster` community, first of all I wanted to thank you for this amazing and useful tool.

**Is your feature request related to a problem? Please describe.**

Sometimes the comments generated automatically by `cpbooster` overlap with my template, which is a bit annoying.

**Describe the solution you'd like**

I want to propose an enhancement option so that in the `configuration file` there is a field that allows to enable and disable the comments that are automatically generated for example these:

```cpp
// time-limit: 2000
// problem-url: https://codeforces.com/contest/1673/problem/C
```
Thank you in advance

**Comment by searleser97** [comment]
without those comments in the file you will have to submit your code manually from the command line, and also, the TLE status will be disabled, could you show an example of how this comments overlap with your template?

**Comment by LuisMBaezCo** [comment]
Ok, I understand you, so far I am using `cpb` and I have not tested the submit option, I will try it.

In that case I think it would not be necessary to implement this new functionality, since looking at it properly, I can solve my problem by modifying my template.

**Comment by searleser97** [comment]
I still wonder how those comments overlap with your template, though 🤔
