### ISSUE TITLE
stderr not seen in `cpb test ...`

### ISSUE THREAD

**Issue by julianferres** [searleser97/cpbooster#62]
I'm trying to use `cerr` inside of my code in C++, but It seems that `stderr` is not shown by the `test` command.

On the other hand, it works with the debug flag activated, but I'm forced to use the prompt and re-enter a test case manually. Is there a way to use `cerr` with the pretests?

(Same situation with `:Test` and `:Debug` in the nvim extension)

**Comment by searleser97** [comment]
does it work with the `debug` flag but sending a problem ID? i.e. without having to insert the testcase manually?

**Comment by searleser97** [comment]
Finally I do not recommend writing to stderr because even if the output does not go to std, it increases the overall time needed for execution, with the template I mentioned this problem disappears

**Comment by julianferres** [comment]
Yes! Adding `-t <id>` seems to have the best of both :) Thank you for suggesting it.

Talking about your template, I also use a trick similar to that to not impact runtime (Using -DLOCAL flag locally):

https://codeforces.com/contest/1690/submission/159836960
