### ISSUE TITLE
Unable to change config path with --configPath

### ISSUE THREAD

**Issue by MohamedIrfanAM** [searleser97/cpbooster#7]
I want to change location of   `~/cpbooster-config.json` to `~/.config/cpbooser/cpbooster-config.json`. But I am unable to change with command `cpb --configPath ~/.config/cpbooster/`. It is giving my error `Not enough non-option arguments: got 0, need at least 1`.

BTW cpbooster is too good, this is exactly what I was searching for. Now I can use neovim instead of VScode :)

**Comment by searleser97** [comment]
I am glad you like cpbooster :D. Now, about your issue, for now you can just specify the `configPath` each time you run a command like `create` , `submit`, ... In other words you cannot change the config path globally/permanently.

As a solution for that, you could create a bash script that runs `cpbooster` with your preferred `configPath`

Final Note: I am planning to add another default location for the config file, which will be `~/.cpbooster/cpbooster-config.json`. So now, `cpbooster` will look for it in `~/cpbooster-config.json` or as second option in `~/. cpbooster/cpbooster-config.json`

**Comment by searleser97** [comment]
I just published the version that looks for your config file in `~/.cpbooster/cpbooster-config.json` and in `~/cpbooster-config.json`

you can update with `npm install cpbooster -g`

-> https://github.com/searleser97/cpbooster/releases/tag/v2.1.0

**Comment by MohamedIrfanAM** [comment]
It would be better if  it was in ` ~/.config/cpbooster/` ( because i don't like to clutter my _Home_ directory ). Any way  its not a big issue..

**Comment by searleser97** [comment]
It shouldn't be hard to add that location as well for the config file.

**Comment by MohamedIrfanAM** [comment]
I moved every config files I can from _Home directory_  to  _~/.config/_

**Comment by searleser97** [comment]
I meant that it shouldn't be hard to add the `.config/cpbooster` directory as an alternative location for `cpbooster-config.json`. I'll add it in next minor update.

**Comment by MohamedIrfanAM** [comment]
Thankyou :)

**Comment by searleser97** [comment]
Done :) 

cpbooster now will also search for the config file in `.config/cpbooster/cpbooster-config.json` by default
