### ISSUE TITLE
cpb uses .exe extensions on all platforms

### ISSUE THREAD

**Issue by shadmansaleh** [searleser97/cpbooster#77]
**Please complete the following information:**
cpbooster version: 2.6.4 
OS: Arch

Using Neovim? : yes
Terminal Name: kitty

**Describe the bug**

cpbooster names complied binaries with .exe extension. .exe only makes sense if user is running windows.
It should probably check if the platform is windows before appending .exe here https://github.com/searleser97/cpbooster/blob/66f20b6424404e8684916d7ca3f326cb022f5405/app/src/Test/TesterFactory/CompiledTester.ts#L124

**Steps To Reproduce it**
1. run any testcase on linux/mac and check the extension of compiled file

**Expected behavior**
.exe should be used on windows only

**Comment by searleser97** [comment]
for now there are no plans to make this change since even though the extension is `.exe` any platform can execute it natively

**Comment by shadmansaleh** [comment]
Because of the .exe extension, It gets sent to wine by default which is kind of dumb.

![image](https://user-images.githubusercontent.com/13149513/219542559-51ceffab-4225-4ea9-8daf-97ec02e43277.png)

And it feels like a 1/2 line change to put a condition there so why not?

**Comment by searleser97** [comment]
In unix (Mac or Linux) systems you can execute your compiled code prepending dot-slash like  `./executable_file.exe`

**Comment by searleser97** [comment]
in progress here: https://github.com/searleser97/cpbooster/pull/89
