### ISSUE TITLE
While testing my code code is showing wrong if I use debug file 

### ISSUE THREAD

**Issue by MdNihal05** [searleser97/cpbooster#92]
When we use our own debug template which prints output for us 

For example [like this](https://pasteboard.co/d2UVkJh7zOho.png)

For more clarity see [here](https://codeforces.com/gym/470085/submission/220931453)

We can submit without removing the debug functions

But when we test using:Test or cpb test it gives WA

It should ignore debug statements and compare actual output 

How to fix that any modifications in config file ?

**Comment by searleser97** [comment]
I am not allowed to see your second link, and the first one is not loading

**Comment by searleser97** [comment]
Please a closer look to this section  

https://searleser97.github.io/cpbooster/docs/debug#print-debug-lines-in-red-in-c

**Comment by MdNihal05** [comment]
thanks for looking in to the issue 

i update the link you can see [here](https://codeforces.com/contest/56/submission/221002916)

and my config file is attached below 
![Screenshot from 2023-08-29 23-10-23](https://github.com/searleser97/cpbooster/assets/112348834/8653a1f6-9205-4787-8a58-f0030c0fc3b3)

and my issue is attached below 
![Screenshot from 2023-08-29 23-13-13](https://github.com/searleser97/cpbooster/assets/112348834/921ada77-573b-4945-8f71-f3f3355dabf6)

i submited the code and got accepted but  where i run cpbooster test file.cpp it showing error because of the debug statements

how should i debug can you share any picture or something so that i can understand 
here is my [templete](https://pastebin.com/zdVh48Dg) and this is my [debug](https://pastebin.com/wgm2zSuW)

**Comment by searleser97** [comment]
your debug statements should no be printing when running Test, could you send an screenshot of the output of your program without using cpbooster? Like compiling with the same command that you have in the config, and then just executing as normal to see if there is any difference in the output

**Comment by MdNihal05** [comment]
you can see here
![Screenshot from 2023-08-29 23-39-13](https://github.com/searleser97/cpbooster/assets/112348834/b239420e-6d00-4da2-b6d1-55000d2fdbdf)

and i can't submit my code while using proxy it's showing error can you fix that

**Comment by MdNihal05** [comment]
you can see here 
![Screenshot from 2023-08-29 23-42-53](https://github.com/searleser97/cpbooster/assets/112348834/ab52a6aa-644d-4d1b-bcef-a9c2a14d651a)

and i can't submit when iam using proxy since i use college proxy iam getting error 

can you fix that

**Comment by searleser97** [comment]
That is the output without your flag ? Then that is the problem, why your debug statements get printed even when you are not passing the debug flag ?

**Comment by searleser97** [comment]
For the proxy thing please create a different issue in this repo, will try to investigate and see if there is something I can do about it

**Comment by MdNihal05** [comment]
it is because i called debug function inside my code  you can see my accepted [submission](https://codeforces.com/contest/56/submission/221002916) this is what i generally do to check my output there is not way to fix it ?

and for proxy thing i will create a new issue thanks

**Comment by searleser97** [comment]
Could you literally run the :Test command with the code from the codeforces link? I mean copy and paste it from codeforces, not from your local machine, and see what is the output in cpbooster

**Comment by MdNihal05** [comment]
i copied the same code i submitted before  and i cloned problem and them submitted the same code 
so i can test but giving wa because of debug statements 

i habitated to looking the outputs by calling debug function if it is correct than i will sumit it directly 

even i did the same here it got sumitted successfully but when i test it it showing wa

so was curious to solve the issue without commenting the debug(....) function in my code

it's taking too long sorry for the inconvenience  and can't we see the status of submissoin in vim itself ?

**Comment by searleser97** [comment]
I just reproduced the issue

**Comment by MdNihal05** [comment]
?

**Comment by searleser97** [comment]
so, I just learned that "codeforces" add the flag "ONLINE_JUDGE" so basically you are doing the opposite, you are saying in your code: If you DON'T see the "ONLINE_JUDGE" flag then print debug stuff, otherwise just hide it, the issue is that then you should add this "ONLINE_JUDGE" flag in the "compilation command"

**Comment by searleser97** [comment]
so that the command from codeforces and from cpbooster is the same

**Comment by searleser97** [comment]
however, I do recommend changing it to the opposite I don't think the "ONLINE_JUDGE" is added by all judges, therefore this might not be compatible if you submit to some other place like AtCode, OmegaUp, etc...

**Comment by MdNihal05** [comment]
you are saying that i should add 
`debugCommand :  g++ -std=gnu++17 -ONLINE_JUDGE -Wshadow -Wall ` instead of `debugCommand :  g++ -std=gnu++17 -DONLINE_JUDGE -Wshadow -Wall `

or something else 

can you tell me where should i change the command what should i add  for specially codeforce because i haven't tried other you don't need to edit in website you can tell here changing flag specially for codeforces

**Comment by searleser97** [comment]
debug command should not include any flag for your code to work, but then in "command" you should include it

**Comment by MdNihal05** [comment]
you mean i should remove 
`#ifdef ONLINE_JUDGE
  coutc << a << " " << b << endlc;
#endif`
from my code ?

**Comment by searleser97** [comment]
no

**Comment by searleser97** [comment]
just modify the "config" file

**Comment by searleser97** [comment]
```json
  "languages": {
    "cpp": {
      "template": "",
      "command": "g++ -std=gnu++17 -DONLINE_JUDGE -O2",
      "debugCommand": "g++ -std=gnu++17 -Wshadow -Wall",
```

**Comment by MdNihal05** [comment]
which statement should i add to this
`anguages : {
 13      cpp : {
 14        template : "",
 15        command :  g++ -std=gnu++17 -O2 ,
 16        debugCommand :  g++ -std=gnu++17 -DONLINE_JUDGE -Wshadow -Wall ,
 17        aliases : {
 18          codeforces :  54 ,
 19          atcoder :  4003 ,
 20          omegaup :  cpp17-gcc ,
 21          szkopul :  C++ ,
 22          yandex :  gcc7_3 
 23       },
 24        type :  compiled ,
 25        commentString :  // 
 26     },`

**Comment by MdNihal05** [comment]
ok thanks  i will try this

**Comment by MdNihal05** [comment]
it worked 
thanks for your patience and you can close this issue 
if you can help me with proxy stuff try to fix it please

**Comment by searleser97** [comment]
however I do recommend to do the opposite as I explain in the documentation link, ONLINE_JUDGE flag will only work for codeforces but not other judge, and I also recommend understanding your template entirely

**Comment by MdNihal05** [comment]
why iam getting this error for atcoder  
iam new to atcoder so i created account and tried to submit
i even tried by changing config to default 
![Screenshot from 2023-08-30 01-38-48](https://github.com/searleser97/cpbooster/assets/112348834/dfab007a-c7cf-4fd7-831d-1f86d4928131)

**Comment by MdNihal05** [comment]
its working fine for codeforces
