### ISSUE TITLE
I can't submit my code using proxy

### ISSUE THREAD

**Issue by MdNihal05** [searleser97/cpbooster#93]
when i tried to submit my code using vim` :Submit` or `cpbooster submit file.cpp` command iam getting error

since i use college proxy i want to know how to fix

i can clone , test , debug  contest using proxy it is performing good when i enter submit command it's showing error

**Comment by searleser97** [comment]
which error are you getting? could you share an screenshot ?

**Comment by MdNihal05** [comment]
![Screenshot from 2023-08-30 10-46-56](https://github.com/searleser97/cpbooster/assets/112348834/8cf3ef27-7bf3-4bab-9a15-5d5fd4d18bdc)
