### ISSUE TITLE
why iam getting this error for atcoder

### ISSUE THREAD

**Issue by MdNihal05** [searleser97/cpbooster#94]
why iam getting this error for atcoder  
iam new to atcoder so i created account and tried to submit
i even tried by changing config to default 

Working fine for codeforces

![Screenshot from 2023-08-30 01-38-48](https://github.com/searleser97/cpbooster/assets/112348834/dfab007a-c7cf-4fd7-831d-1f86d4928131)

_Originally posted by @MdNihal05 in https://github.com/searleser97/cpbooster/issues/92#issuecomment-1698064780_

**Comment by searleser97** [comment]
Could you try submitting your file without cpbooster and see if atcoder displays any error message ?

**Comment by MdNihal05** [comment]
without cpbooster ? in website itself right 

then see [submission](https://atcoder.jp/contests/practice/submissions/45052907) if you can access this

**Comment by searleser97** [comment]
probably they updated the website somehow and now cpbooster is having issue, will test this later today, thanks for reporting

**Comment by MdNihal05** [comment]
Thanks
Hope you will fix this soon

**Comment by MdNihal05** [comment]
Can we see submit status in terminal itself 
Like we can see submit status after submitting in 
`cph ( compititive programming helper vs code)`
`cp-editor`
See [reference](https://codeforces.com/blog/entry/72952)

**Comment by searleser97** [comment]
![image](https://github.com/searleser97/cpbooster/assets/5056411/8f8078b8-786c-4324-b52f-916aab83f9bb)

**Comment by searleser97** [comment]
Looks like atcoder changed the id for C++ take a look at  

https://searleser97.github.io/cpbooster/docs/submit#how-to-configure-language-aliases and update your cpbooster-config file accordingly to your needs. For example set atcoder alias to `5001` instead of `4003` for cpp language

**Comment by searleser97** [comment]
fixed with https://github.com/searleser97/cpbooster/commit/cdfbd6fe91dcde76c101922718542002f934689c
