### ISSUE TITLE
CBCM is not enabled

### ISSUE THREAD

**Issue by mohammadrehan28** [searleser97/cpbooster#97]
**Please complete the following information:**
cpbooster version: 2.6.5
OS: Arch
Using Vim? : no
Using Neovim? : yes
Terminal Name: Konsole

**Describe the bug**
when i try to login to any website like codeforces or atcoder i show this error.

**Screenshots**
![Screenshot_20230904_183258](https://github.com/searleser97/cpbooster/assets/65272881/655d6169-9376-4a75-923d-1d83efd8a5e8)
![Screenshot_20230904_183321](https://github.com/searleser97/cpbooster/assets/65272881/ebff123b-e75f-437e-a855-15adac4ab61f)

**Comment by searleser97** [comment]
Could you share which version of `nodejs` are you using ?

**Comment by searleser97** [comment]
related to #96

**Comment by searleser97** [comment]
I was not able to repro this issue, I am using konsole in KDE Neon with node v20.5.1 and it is working fine, Could you try reinstalling ?

**Comment by searleser97** [comment]
actually could you share the command you use to install ?

**Comment by searleser97** [comment]
following up on #96
